# Generated by Django 5.2.6 on 2025-09-07 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('lineup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('day', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('tentative', 'Provisoire'), ('confirmed', 'Confirmé'), ('canceled', 'Annulé')], db_index=True, default='tentative', max_length=10)),
                ('is_headliner', models.BooleanField(db_index=True, default=False)),
                ('setlist_urls', models.JSONField(blank=True, default=list, help_text='["https://..."]')),
                ('tech_rider', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='lineup.artist')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.festivaledition')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='core.stage')),
            ],
            options={
                'ordering': ['day', 'stage__name', 'start_time'],
                'indexes': [models.Index(fields=['edition', 'day', 'stage', 'start_time'], name='schedule_sl_edition_e34098_idx')],
            },
        ),
    ]
