# Generated by Django 5.2.6 on 2025-09-07 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, help_text='Code ISO-3166-1 alpha-2 (FR, BE, …)', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('map_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FestivalEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('year', models.PositiveIntegerField(db_index=True, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('hero_image', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-year'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='core_festiv_start_d_ad1b17_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(choices=[('press', 'Presse'), ('artist_rel', 'Relations artistes'), ('public', 'Public'), ('tech', 'Technique')], max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.festivaledition')),
            ],
            options={
                'unique_together': {('edition', 'type', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('covered', models.BooleanField(default=False)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.festivaledition')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='core.venue')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('edition', 'name')},
            },
        ),
    ]
