# Generated by Django 5.2.6 on 2025-09-08

from django.db import migrations, models
import django.db.models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivaledition',
            name='name_i18n',
            field=models.JSONField(default=dict, blank=True, help_text="Traductions: {'fr': 'Nom', 'en': 'Name', ...}"),
        ),
        migrations.AddField(
            model_name='festivaledition',
            name='tagline_i18n',
            field=models.JSONField(default=dict, blank=True, help_text="Traductions: {'fr': 'Accroche', 'en': 'Tagline', ...}"),
        ),
    ]
