# Generated by Django 5.2.6 on 2025-09-08 09:33

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_i18n_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festivaledition',
            name='name_i18n',
        ),
        migrations.RemoveField(
            model_name='festivaledition',
            name='tagline_i18n',
        ),
        migrations.AlterField(
            model_name='venue',
            name='country',
            field=models.CharField(blank=True, help_text='Code ISO-3166-1 alpha-2 (FR, BE, …)', max_length=2, validators=[apps.common.validators.validate_country_iso2]),
        ),
    ]
