# Generated by Django 5.2.6 on 2025-09-08 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_festivaledition_name_i18n_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="edition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="core.festivaledition",
            ),
        ),
        migrations.AlterField(
            model_name="stage",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stages",
                to="core.venue",
            ),
        ),
    ]
