# Generated by Django 5.2.6 on 2025-09-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_stage_edition_alter_stage_venue"),
    ]

    operations = [
        migrations.AddField(
            model_name="festivaledition",
            name="name_i18n",
            field=models.JSONField(
                blank=True, default=dict, help_text="Traductions du nom"
            ),
        ),
        migrations.AddField(
            model_name="festivaledition",
            name="tagline_i18n",
            field=models.JSONField(
                blank=True, default=dict, help_text="Traductions de l'accroche"
            ),
        ),
    ]
