# Generated by Django 5.2.6 on 2025-09-07 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.CharField(max_length=240)),
                ('answer_md', models.TextField()),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.festivaledition')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('review', 'Relecture'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=12)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('unpublish_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('body_md', models.TextField()),
                ('cover', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='["annonce","lineup"]')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.festivaledition')),
            ],
            options={
                'ordering': ['-publish_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('review', 'Relecture'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=12)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('unpublish_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('body_md', models.TextField(help_text='Markdown')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.festivaledition')),
            ],
            options={
                'ordering': ['slug'],
                'unique_together': {('edition', 'slug')},
            },
        ),
    ]
