# Generated by Django 5.2.6 on 2025-09-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
