# Generated by Django 5.2.6 on 2025-09-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('review', 'Relecture'), ('published', 'Publié'), ('archivé', 'Archivé')], db_index=True, default='draft', max_length=12),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('review', 'Relecture'), ('published', 'Publié'), ('archivé', 'Archivé')], db_index=True, default='draft', max_length=12),
        ),
    ]
