# Generated by Django 5.2.6 on 2025-09-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsortier',
            name='rank',
            field=models.PositiveIntegerField(db_index=True, default=100),
        ),
    ]
