# Generated by Django 5.2.6 on 2025-09-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_festivaledition_name_i18n_and_more'),
        ('sponsors', '0002_alter_sponsortier_rank'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sponsorship',
            index=models.Index(fields=['edition', 'visible', 'tier', 'order'], name='sponsors_sp_edition_039656_idx'),
        ),
    ]
