# Generated by Django 5.2.6 on 2025-09-07 20:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('color', models.CharField(blank=True, help_text='#RRGGBB', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('country', models.CharField(blank=True, help_text='ISO-3166-1 alpha-2', max_length=2)),
                ('short_bio', models.TextField(blank=True)),
                ('long_bio', models.TextField(blank=True)),
                ('picture', models.URLField(blank=True)),
                ('banner', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('socials', models.JSONField(blank=True, default=dict, help_text='{"instagram":"", "youtube":"", "spotify":""}')),
                ('external_ids', models.JSONField(blank=True, default=dict, help_text='{"musicbrainz":"", "spotify":"..."}')),
                ('popularity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('genres', models.ManyToManyField(blank=True, related_name='artists', to='lineup.genre')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateField()),
                ('available', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='lineup.artist')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('artist', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['popularity'], name='lineup_arti_popular_2ddd8f_idx'),
        ),
    ]
