# Generated by Django 5.2.6 on 2025-09-08 12:17

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.CharField(blank=True, help_text='ISO-3166-1 alpha-2', max_length=2, validators=[apps.common.validators.validate_country_iso2]),
        ),
    ]
