# Generated by Django 5.2.6 on 2025-09-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineup", "0002_alter_artist_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="banner",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="artist",
            name="picture",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="artist",
            name="website",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
