# Generated by Django 5.2.6 on 2025-09-07 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(db_index=True, help_text='ex: PASS1J, PASS3J, EARLY', max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('day', models.DateField(blank=True, help_text='Si billet 1 jour, renseigner la date', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(choices=[('EUR', 'Euro')], default='EUR', max_length=3)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='TVA %', max_digits=4)),
                ('quota_total', models.PositiveIntegerField(default=0)),
                ('quota_reserved', models.PositiveIntegerField(default=0)),
                ('sale_start', models.DateTimeField(blank=True, null=True)),
                ('sale_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='core.festivaledition')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('edition', 'code')},
            },
        ),
    ]
