# Generated by Django 5.2.6 on 2025-09-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='code',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
