# Generated by Django 5.2.6 on 2025-09-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_v2_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tickettype',
            new_name='tickets_tic_edition_4bf338_idx',
            old_name='tickets_typ_edition_phase_active_idx',
        ),
        migrations.RenameIndex(
            model_name='tickettype',
            new_name='tickets_tic_edition_b4a2af_idx',
            old_name='tickets_typ_edition_day_active_idx',
        ),
    ]
